### ISSUE TITLE
Добавление несуществующего пира

### ISSUE THREAD

**Issue by waterwa1ker** [drveles-X-zkhrg/campus_map_bot#37]
Всем привет! Проект хороший, не сочтите за дерзость) 

При добавление пира в список отслеживания можно ввести абсолютно любой ник (скрин приложу), поэтому было бы классно добавить предупреждающую надпись о том, что пир не найден (либо сделать какую-нибудь пагинацию, а потом уже осуществлять поиск пира)

![image](https://github.com/drveles-X-zkhrg/campus_map_bot/assets/93448687/e997e70e-273a-4f6d-8714-bbe5ff7fcb4c)

**Comment by DrVeles** [comment]
Привет! Спасибо за обратную связь)
Мы думали об этом, и приняли решение оставить это под ответственность пользователей. 
Если окажется очень актуально пересмотрим подход.

**Comment by waterwa1ker** [comment]
> Привет! Спасибо за обратную связь) Мы думали об этом, и приняли решение оставить это под ответственность пользователей. Если окажется очень актуально пересмотрим подход.

Как вариант) Хозяин - барин, как говорится
